# Site settings
baseurl = "http://wavecos.github.io"
languageCode = "en-us"
title = "wavecos"
theme = "hugo-cactus-theme"
# Enter your tracking code to enable Google Analytics
googleAnalytics = "UA-70425689-1"
# Disable comments by leaving disqusShortname empty
disqusShortname = "onix"

[params]
	name = "Alfredo Arias"
	description = "Describe your website"
	bio = "Software Developer - Geek - Guitar Player"
	# Enter optionally your twitter account
	twitter = "wavecos"
	enableRSS = true

	# Add custom assets with their paths relative to the static folder
	customCSS = []
	customJS  = []

	# The variables below are optionally too and can be used to
	# translate or customize each string of the theme.

	# Navigation links
	home = ""
	about = ""
	subscribe = ""
	# Pagination links
	olderPosts = ""
	newerPosts = ""
	readMore = ""
	copyright = ""
	# Sharing options and author information in posts
	aboutAuthor = "I'm an enthusiastic developer"
	tweet = ""
	share = ""
	# 404 page
	title404 = ""
	subtitle404 = ""

	# Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
	iconFont = "mono-social"
    # The social icons can be styled differently if you use mono as font - circle, rounded, or empty
    socialIconStyle = "circle"

# Add additional social link entries underneath
[social]
    twitter  = "https://www.twitter.com/wavecos"
    facebook = "https://www.facebook.com/"
    github   = "https://www.github.com/wavecos"
    # dribble  = "https://www.dribbble.com/"
